# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170906_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='keyword',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
