# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170907_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='keyword',
            field=models.CharField(max_length=80),
        ),
    ]
