# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_usercode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercode',
            unique_together=set([('user', 'code')]),
        ),
    ]
