# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
