# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170912_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable1',
        ),
    ]
