# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_opportunity_useropportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='opportunity',
            unique_together=set([('url', 'title')]),
        ),
    ]
