# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170913_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Keyword Opportunities',
            },
        ),
        migrations.RemoveField(
            model_name='useropportunity',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='useropportunity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useropportunity',
            name='user_code',
        ),
        migrations.RemoveField(
            model_name='useropportunity',
            name='user_keyword',
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AddField(
            model_name='keyword',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserOpportunity',
        ),
        migrations.AddField(
            model_name='keywordopportunity',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Keyword'),
        ),
        migrations.AddField(
            model_name='keywordopportunity',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Opportunity'),
        ),
    ]
