# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170913_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Code Opportunities',
            },
        ),
        migrations.AddField(
            model_name='code',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeopportunity',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Code'),
        ),
        migrations.AddField(
            model_name='codeopportunity',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Opportunity'),
        ),
    ]
