# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170920_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_id',
            field=models.CharField(default=b'11', max_length=80, unique=True),
        ),
    ]
