# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_code_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='posted_on',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
