# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_useropportunityrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useropportunityrequest',
            old_name='code',
            new_name='codes',
        ),
        migrations.RenameField(
            model_name='useropportunityrequest',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
