# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171015_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
