# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_auto_20171015_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('codes', models.ManyToManyField(to='blog.Code')),
                ('keywords', models.ManyToManyField(to='blog.Keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Requests',
            },
        ),
        migrations.CreateModel(
            name='UserRequestOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Opportunity')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserRequest')),
            ],
            options={
                'verbose_name_plural': 'User Request Opportunities',
            },
        ),
        migrations.RemoveField(
            model_name='useropportunityrequest',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='useropportunityrequest',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='useropportunityrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserOpportunityRequest',
        ),
    ]
