# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20171015_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestopportunity',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_opportunities', to='blog.UserRequest'),
        ),
    ]
